### PR TITLE
Assign all txs a temp key so when error due to user metamask rejectio…

### LINKED ISSUE #134: if reject transaction in metamask undefined key is added in transaction object
if you click on reject transaction in metamask a undefined key is added in the transaction object, its not a critical bug i think, but at first glance its weird, im running the latest version of metamask extension and the latest version of drizzle 1.2.4, cheers

image

pd: i think is because there is not txhash , because the transaction hasnt even started

### PR DESCRIPTION
**Pull request by honestbonsai**
…n, we can still look them up

Fixes #134

### CODE REVIEW

**Comment by honestbonsai** [comment]
Should probably also write what the error was to the `transactions` reducer. Console logs show 

```
MetaMask - RPC Error: Error: MetaMask Tx Signature: User denied transaction signature. {code: -32603, message: "Error: MetaMask Tx Signature: User denied transaction signature."}
...
17:18:24.516 index.js:2178 Error: Returned error: Error: MetaMask Tx Signature: User denied transaction signature.
    at Object.ErrorResponse (errors.js:29)
```

But the action receives an empty error object.

In progress...

EDIT: fixed

**Comment by adrianmcli** [comment]
@honestbonsai I don't love it, but it's better than the current behaviour so I'm all for it.

But I also see a lot of formatting changes, did you try running `npm run format`? If not, it might be good to do that before we merge this PR.

**Comment by honestbonsai** [comment]
@adrianmcli Thanks for pointing that command out, I ran it and it did remove most of the formatting changes that were made by my editor. Changes should be a lot cleaner now.

**Comment by adrianmcli** [comment]
Cool, btw I made an issue about integrating lint-staged: https://github.com/trufflesuite/drizzle/issues/161

LGTM!

**Pull request merged**
