### PR TITLE
Bugfix for TX processing problem introduced in 1.1.5

### PR DESCRIPTION
**Pull request by protolambda**
The fix for address comparisons introduced in 1.1.5 did not account for the special case where "to" is undefined (e.g. a contract deploy TX). This should fix it, and also includes the same check for the "from" property, just in case.

### CODE REVIEW

**Comment by yvon** [comment]
Nice! I think you forgot to re-build the dist folder.

I created a PR on your branch: https://github.com/protolambda/drizzle/pull/1

**Comment by protolambda** [comment]
@yvon I didn't forget it, I just purposefully didn't include it. There shouldn't be a dist folder on git in the first place. And including a build output file of over 6K lines in each and every PR makes tracking actual source code changes only more difficult.

Can you consider changing the build process please? I think npm has install-hooks that you can use to make the dist folder build after installing the package.

**Comment by protolambda** [comment]
@yvon Nvm, I think @DiscRiskandBisque is the right person to address the dist folder change to. I'm certainly not going to keep updating a dist folder in each future PR...

**Comment by DiscRisknBisque** [comment]
Thanks @protolambda ! Regarding the `/dist` folder: I default to excluding it as well, but there were requests to have it in there as a sort of quick-n-dirty nightly if someone wants to bleeding edge dev version. Your intuition was correct: No need to worry about rebuilding it in PRs--I'll do that myself after merger.

**Pull request merged**
