### PR TITLE
Added features, usable in Redux projects, works with Metamask

### PR DESCRIPTION
**Pull request by balasan**
Apologies for a very big PR.

## General build updates
- Refactor webpack config to not include dependencies in the build
- Remove `dist` from `.gitignore` for easy npm installs via github

## Overview of New Features
- Drizzle now watches and updates account balances
  - Breaking change: accounts state now contains `ids` and `balances` fields (see README)
- Ability to use Metamask for accounts and sending/signing transactions (includes PR #15)
- Easier access to contract methods via store
  - Breaking change: contracts state is now stored in a `state` objects to avoid any naming collisions (see README)
- Moved initialization of contract state from `generateStore.js` to `DrizzleContracts.js`
- Added `reducer` and `rootSaga` to exports for use in existing redux projects

here is an example of using drizzle + Metamask in an existing redux app: https://github.com/relevant-community/bonding-curve-component/tree/redux/demo

closes: #10, #11 (and #20 sorta)

### CODE REVIEW

**Comment by balasan** [comment]
Ah just saw that the develop branch has diverged a bit @DiscRiskandBisque let me know if you're interested in incorporating any of these — especially getting it to work with existing redux projects and I can take a stab at the develop branch.

**Comment by tarrencev** [comment]
Would love the webpack changes to be merged asap

**Comment by balasan** [comment]
hey @tarrencev this PR is out of date with the master branch at this point, but I opened a separate one here #26 with just the webpack changes — hoping it will get merged soon!

**Comment by balasan** [comment]
closing this because its outdated - newer PRs include most of these updates

**Pull request closed without merging**
