### PR TITLE
Web3 Contract Instance Support

### PR DESCRIPTION
**Pull request by asselstine**
This PR:

1. Allows Web3 Contract instances to be used as in:

```
// drizzle options

export default {
  // ...
  contracts: [
    truffleArtifact, // regular artifact
    {
      contractName: 'TestContract',
      web3Contract: new web3.eth.Contract(/* abi, address etc */)
    }
  ]  
}
```

2. Changes the window.onload listener to bind instead to a promise, so that Drizzle can be initialized asynchronously

3. Fixes a word in the README.md.

### CODE REVIEW

**Comment by DiscRisknBisque** [comment]
Closing this and merging #64 (see reply there).

**Comment by Bowfish** [comment]
I have aquestion

**Comment by Bowfish** [comment]
I have the following code
```javascript
import Test from './Test.sol'

this.LogFactory.methods.getTestContract(this.props.accounts[0]).call().then( (testContractAddress) => {	
	const contractConfig = {
		contractName: 'Test',
		web3Contract: new this.web3.eth.Contract(
			Test.abi,
			testContractAdress
		)
	}
}).catch((error) => {
	console.log(error)
})

const events = ['Mint']

context.drizzle.addContract(Test, {contractConfig, events})

console.log(context.drizzle)
```

With this, the contract Test is created at an arbitrary address and not with the address that I specified. How can I make sure, that the contract is added with the address which is in `testContractAddress`? The `testContractAddress`comes from a contract which is created by a `new Test` in the `LogFactory`contract in solidity and I need to use the contract at this address.

**Comment by igorline** [comment]
@Bowfish, I was able to add contract properly by passing 2 arguments to `addContract` method: contract config and events array

In your case it should be like: `context.drizzle.addContract(contractConfig, events)`

**Comment by lundrimazemi** [comment]
Hello is there any tutorial on how we can add contracts dynamically ex. we deploy a contractFactory and then we use it to generate new contracts by filling a form from a user and then interact with it. Thanks

**Comment by cds-amal** [comment]
Hi @lundrimazemi,

Can you open a new issue so we can track the conversation? Please include a repo with the ContractFactory contract. This is an interesting use case!

**Comment by pau1m** [comment]
@lundrimazemi docs here https://www.trufflesuite.com/docs/drizzle/getting-started/contract-interaction#adding-contracts-dynamically

**Pull request closed without merging**
