### PR TITLE
Fix/metamask 6.6.0 breaks access denied

### PR DESCRIPTION
**Pull request by dannycarrera**
Patch for #230 

This change allows for the same behavior to continue since before the MetaMask 6.6.0 update, where drizzle still initializes web3 but no accounts are available. This is only a patch for v1.4 as #224 introduces the WEB3_USER_DENIED status.

### CODE REVIEW

**Comment by adrianmcli** [comment]
@cds-amal what's going on with the reverting of the version numbers here?

**Review by cds-amal — CHANGES_REQUESTED** [review]
Hi @dannycarrera, thank you for this PR! 

  - Rebase to the v1.4 branch. The PR note mentions a fix for the 1.4 branch but code is based on the v1.3 branch. 
  - Please add tests to document the expected behavior of the new code. This will help us verify, track and and maintain the feature as the project evolves. Examples of tests are in `test/web3.test.js` . Feel free to ask in comments if you need assistance.

Thanks again for contributing to our project

**Comment by cds-amal** [comment]
Thanks for pointing that out @adrianmcli

**Comment by dannycarrera** [comment]
Thanks for the feedback @cds-amal.

I mistakenly based off of the 1.4 tag. Rebased to the release/1.4 branch, added a test and create a new PR #232. Closing this one.

**Pull request closed without merging**
