### PR TITLE
Some dependencies update

### PR DESCRIPTION
**Pull request by MrRefactoring**

### CODE REVIEW

**Comment by adrianmcli** [comment]
@cds-amal What's the status on reviewing this PR?

**Comment by cds-amal** [comment]
@MrRefactoring Thanks for this! It solves some Jest issues for us.

With your changes and introduction of `.babelrc`, `jest.config.js` no longer needs the `transform` rule and `jest.transform.js` can be removed. Is that correct? If it is can you also modify those files.

Thanks again!

**Comment by MrRefactoring** [comment]
Thanks for the review! I also wanted to update `redux-saga` and `web3`, but this causes some errors when testing. Can we review these errors together if I create another PR?

**Comment by cds-amal** [comment]
@MrRefactoring Thanks again for this update.

Please create a separate PR for redux-saga and I'll be happy to work with you on that. I feel that upgrading to redux-saga will need some care and more tests because [redux-saga v1.0 introduced a number of breaking changes](https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0) that have to be accounted for.

**Comment by cds-amal** [comment]
This looks good @MrRefactoring. I'll run integration tests against DRC and Drizzle box as a final confidence test.

**Pull request merged**
