### PR TITLE
Redux saga updated

### PR DESCRIPTION
**Pull request by MrRefactoring**
Thanks for the link to changes in redux-saga. I was able to update redux-saga

### CODE REVIEW

**Comment by cds-amal** [comment]
Thank you for this @MrRefactoring! Updating the current tests to make them pass is a great start to upgrade to redux-saga v1.0. 

I want to make sure we cover our bases on a major version upgrade. This includes reviewing/changing/approving the code as conforming to the new Saga's API, where necessary and addressing outstanding sagas issues like #171, #193 and others. I think it's probably best to identify the work up front so we can more easily handle/track the work. I will tag you when that's done.

**Comment by 0xTimepunk** [comment]
ETA for this? :)  

Thanks for the great work

**Comment by adrianmcli** [comment]
@MrRefactoring Thanks so much for making this PR! Unfortunately, we're in the process of moving over to a monorepo and this seems like a relatively simple to replicate PR for the new monorepo. Do you mind if we include this change after the move? Sorry for not addressing this PR earlier.

**Comment by MrRefactoring** [comment]
@adrianmcli, yes sure

**Comment by MrRefactoring** [comment]
Some of the changes moved #238 PR. It also contains changes that will lead to errors when using

**Pull request closed without merging**
