### PR TITLE
Feature/react native

### LINKED ISSUE #130: Support for React Native
Supporting React Native would be quite helpful. There are a few things that's needed to make everything happy.

1. Initialization assumes a `window.addEventListener` which doesn't exist in RN (see #100)

2. Shims need to be in place for node/browser dependencies that don't exist in RN. Probably this should just be documented.

	**At the top of your entry point**
	```js
	// App.js or index.js
	
	import 'node-libs-react-native/globals';
	import { URL, URLSearchParams } from 'whatwg-url';
	import { btoa } from 'Base64';
	
	global.URL = URL;
	global.URLSearchParams = URLSearchParams;
	global.btoa = btoa;
	```
	
	**Configuration passed to react native cli**
	
	```js
	// rn-cli.config.js (>0.57)
	
	module.exports = {
	  resolver: {
	    extraNodeModules: require('node-libs-react-native')
	  }
	};
	```

3. The Webpack distribution is somehow incompatible outside of a browser 🤷‍♀️. Including the `src` directory and adding `"react-native": "src/index.js",` allows the metro bundler to compile it itself and it seems to be happy. 

	**Current Workaround**
    Add drizzle as a git dependency 
 😢 `git+https://github.com/trufflesuite/drizzle.git#1.2.3` and add a post-install script to inject the prop to allow metro to find the correct files

	<details>
	  <summary>Post install script</summary>
	
  	  ```js
	  const fs = require('fs-extra');
	  const drizzlePackage = require('../node_modules/drizzle/package.json');
	
	  (async () => {
	    // https://github.com/trufflesuite/drizzle/issues/130
	    drizzlePackage['react-native'] = './src/index.js';
	
	    await fs.writeFile(
	      './node_modules/drizzle/package.json',
	      JSON.stringify(drizzlePackage, null, 2)
	    );
	  })().catch(console.log);
	  ```
	</details>

	<details>
	  <summary>Current Unhelpful error for those interested</summary>
	  
	  ```log
	    console.error: "Unhandled promise rejection", {"line":98217,"column":34,"sourceURL":"http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false"}
	
		error
		    YellowBox.js:59:8
		<unknown>
		    drizzle.js:2583:24
		exports
		    drizzle.js:1826:30
		<unknown>
		    drizzle.js:2577:23
		_callTimer
		    JSTimers.js:152:14
		_callImmediatesPass
		    JSTimers.js:200:17
		callImmediates
		    JSTimers.js:464:30
		__callImmediates
		    MessageQueue.js:320:6
		<unknown>
		    MessageQueue.js:135:6
		__guard
		    MessageQueue.js:297:10
		flushedQueue
		    MessageQueue.js:134:17
	  ```
	</details>

### PR DESCRIPTION
**Pull request by honestbonsai**
Fixes #130 

Big thanks to @barlock @soundyogi for their input and feedback!

### CODE REVIEW

**Comment by barlock** [comment]
LGTM, did you find out how the package is published? Without that the src directory will be missing still.

**Comment by honestbonsai** [comment]
@barlock Yup, `src/` will be in the next release, thanks for the follow up on that.

**Comment by soundyogi** [comment]
Awesome!
This is what Open Source is about. 

It was a pleasure.

Great Work @honestbonsai !!!!!!

<3 <3 <3

**Comment by adrianmcli** [comment]
Lgtm

**Pull request merged**
